server:
  port: 9081

spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      properties:
        schema:
          registry:
            url: "http://localhost:8081"
    consumer:
      group-id: "spring-boot-avro-consumer-id"
      autoOffsetReset: "earliest"
      properties:
        schema:
          registry:
            url: "http://localhost:8081"
        specific:
          avro:
            reader: "true"



avro:
  topic:
    name: "library"


