server:
  port: 9081

  ssl:
    enabled: false

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 231591f4acafd18ddef9
            client-secret: 26e43539838de343f0eeae85c10c729b17e5f970
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=library;encrypt=false
    username: sa
    password: test@123
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      keySerializer: "org.apache.kafka.common.serialization.StringSerializer"
      valueSerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: "http://localhost:8081"
    consumer:
      group-id: "spring-boot-avro-consumer-id"
      keyDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      valueDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      autoOffsetReset: "earliest"
      properties:
        schema:
          registry:
            url: "http://localhost:8081"
        specific:
          avro:
            reader: "true"

avro:
  topic:
    name: "library"

